    #app properties
videoapp.worker.temporal-output-directory=${TRANSCODE_TEMP_DIR:/tmp/processing}
videoapp.worker.job-next-retry-delay-sec=600

    #aws s3
aws.s3.bucket-name=${AWS_S3_BUCKET:}
aws.s3.presigned-url-lifetime-sec=${AWS_S3_PRESIGNED_URL_LIFETIME_SEC:180}
#15mb
aws.s3.max-part-upload-size=${MAX_PART_UPLOAD_SIZE:15728640}

    #aws credentials
aws.access.key.id=${AWS_ACCESS_KEY_ID:}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY:}
aws.region=${AWS_REGION:eu-central-1}

    #aws events
aws.sqs.video-processing-queue=${AWS_SQS_QUEUE_NAME:}

    #db
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL:10}
